version: '3'
services:
  middleware:
    container_name: middleware
    image: custom-middleware-notls
    build:
      context: ..
      dockerfile: custom-middleware-docker/custom-middleware.dockerfile
    depends_on:
      - broker
      - db
    tty: true
    stdin_open: true
    environment:
      mqtt_host: broker
      mqtt_port: 8883
      mqtt_tls_enabled: 1
      cafile: /middleware/config/certs/ca.crt
      certfile: /middleware/config/certs/client.crt
      keyfile: /middleware/config/certs/client.key
      redis_host: db
      redis_port: 6379
  broker:
    container_name: broker
    image: eclipse-mosquitto:latest
    ports:
      - "8883:8883"
    volumes:
      - "../config/certs:/mosquitto/config/certs"
      - "./mosquitto/mosquitto.tls.conf:/mosquitto/config/mosquitto.conf"
  db:
    container_name: db
    image: redis:latest
    ports:
      - "6379:6379"
